### ISSUE TITLE
Add `transcoderCount` to protocol/day/round entity

### ISSUE THREAD

**Issue by adamsoffer** [livepeer/subgraph#51]
Looks like we're currently relying on `numActiveTranscoders` which is a fixed parameter that represents that max number of active transcoders allowed, not the total number of current active transcoders. To index count we'll need to increment a `transcoderCount` field any time a transcoder is activated and decrement anytime a transcoder is deactivated.

**Comment by adamsoffer** [comment]
Alternatively you can use the contract function `getTranscoderPoolSize()` whenever a new round is initialized and set the count for the protocol, day, and round entity in there.

**Comment by 0xcadams** [comment]
Sounds good, I will modify this to be the actual number of transcoders, instead of the cap
