### ISSUE TITLE
Update uniswap eth/dai pair with eth/usdc pair in arbitrum pool for explorer fee chart data

### ISSUE THREAD

**Issue by adamsoffer** [livepeer/subgraph#6]
We use a helper to get the pool address. https://github.com/livepeer/subgraph/blob/confluence/utils/helpers.ts#L272

We'll need to create a new helper function that returns the eth/usdc price on uniswap v3 arbitrum 

https://info.uniswap.org/#/arbitrum/pools/0xc31e54c7a869b9fcbecc14363cf510d1c41fa443

**Comment by yondonfu** [comment]
Why the switch from ETH/DAI to ETH/UDSC? Does the ETH/UDSC pair have more liquidity on Arbitrum?

**Comment by adamsoffer** [comment]
Yeah I noticed the ETH/USDC pair had millions in liquidity vs a 300k in the DAI pool. Probably doesn't matter though as they'll both should have the same exchange.
