### ISSUE TITLE
updatePollTallyOnEarningsClaimed failing

### ISSUE THREAD

**Issue by 0xcadams** [livepeer/subgraph#88]
The subgraph on Arbitrum Rinkeby is failing due to a missing function in `src/mappings/pollTallyHandlers.ts`: `updatePollTallyOnEarningsClaimed`

**Comment by adamsoffer** [comment]
Fixed here: https://github.com/livepeer/subgraph/commit/0fab0775d831d5d3af6868e02891c22b5586f92f
